version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      # Installing dependencies
      - yarn
  pre_build:
    commands:
      # Running lint, prettier and tests
      - yarn lint
      - yarn lint:fixprettier
      - yarn test
  build:
    commands:
      # Packaging the application by using Serverless Framework
      - yarn workspace gc-api serverless package
  post_build:
    commands:
      # Deploying the application by using Serverless Framework
      - yarn workspace gc-api serverless deploy:$STAGE
      # Application info by using Serverless Framework
      - yarn workspace gc-api serverless info:$STAGE
